/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentExperienceRouteImport } from './routes/student-experience'
import { Route as ProgrammeInformationRouteImport } from './routes/programme-information'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerOpportunitiesRouteImport } from './routes/career-opportunities'
import { Route as IndexRouteImport } from './routes/index'

const StudentExperienceRoute = StudentExperienceRouteImport.update({
  id: '/student-experience',
  path: '/student-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeInformationRoute = ProgrammeInformationRouteImport.update({
  id: '/programme-information',
  path: '/programme-information',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerOpportunitiesRoute = CareerOpportunitiesRouteImport.update({
  id: '/career-opportunities',
  path: '/career-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/contact': typeof ContactRoute
  '/programme-information': typeof ProgrammeInformationRoute
  '/student-experience': typeof StudentExperienceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/contact': typeof ContactRoute
  '/programme-information': typeof ProgrammeInformationRoute
  '/student-experience': typeof StudentExperienceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/contact': typeof ContactRoute
  '/programme-information': typeof ProgrammeInformationRoute
  '/student-experience': typeof StudentExperienceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career-opportunities'
    | '/contact'
    | '/programme-information'
    | '/student-experience'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career-opportunities'
    | '/contact'
    | '/programme-information'
    | '/student-experience'
  id:
    | '__root__'
    | '/'
    | '/career-opportunities'
    | '/contact'
    | '/programme-information'
    | '/student-experience'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerOpportunitiesRoute: typeof CareerOpportunitiesRoute
  ContactRoute: typeof ContactRoute
  ProgrammeInformationRoute: typeof ProgrammeInformationRoute
  StudentExperienceRoute: typeof StudentExperienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-experience': {
      id: '/student-experience'
      path: '/student-experience'
      fullPath: '/student-experience'
      preLoaderRoute: typeof StudentExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme-information': {
      id: '/programme-information'
      path: '/programme-information'
      fullPath: '/programme-information'
      preLoaderRoute: typeof ProgrammeInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-opportunities': {
      id: '/career-opportunities'
      path: '/career-opportunities'
      fullPath: '/career-opportunities'
      preLoaderRoute: typeof CareerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerOpportunitiesRoute: CareerOpportunitiesRoute,
  ContactRoute: ContactRoute,
  ProgrammeInformationRoute: ProgrammeInformationRoute,
  StudentExperienceRoute: StudentExperienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
